5 LINHAS EM CADA TABELA

INSERT INTO PAIS VALUES (1, 'BRASIL');
INSERT INTO PAIS VALUES (2, 'CANADA');
INSERT INTO PAIS VALUES (3, 'MEXICO');
INSERT INTO PAIS VALUES (4, 'CHINA');
INSERT INTO PAIS VALUES (5, 'JAPAO');

COMMIT;

INSERT INTO ESTADO VALUES (1, 'SAO PAULO');
INSERT INTO ESTADO VALUES (2, 'RIO DE JANEIRO');
INSERT INTO ESTADO VALUES (3, 'CURITIBA');
INSERT INTO ESTADO VALUES (4, 'MINAS GERAIS');
INSERT INTO ESTADO VALUES (5, 'RORAIMA');
COMMIT;

INSERT INTO CIDADE VALUES (1, 'SAO PAULO');
INSERT INTO CIDADE VALUES (2, 'RIO DE JANIEOR');
INSERT INTO CIDADE VALUES (3, 'DIADEMA');
INSERT INTO CIDADE VALUES (4, '');
INSERT INTO CIDADE VALUES (5, '');




